name: ci

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: checkout
        uses: actions/checkout@v1

      - name: ensure-containers-exist
        run: |
          docker-compose up -d && docker-compose down

      - name: integration-tests
        run: sudo make integration-tests
